### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by yc0313** [IZAY01/LibcSearcher#10]
出现错误提示：TypeError: string indices must be integers
Traceback (most recent call last):
  File "/home/yc0313/pwn/test.py", line 4, in <module>
    obj.dump("printf") # 根据已有约束条件，查询某个符号在 Libc 中的地址
  File "/home/yc0313/.local/lib/python3.8/site-packages/LibcSearcher/LibcSearcher.py", line 68, in dump
    self.determine_the_libc()
  File "/home/yc0313/.local/lib/python3.8/site-packages/LibcSearcher/LibcSearcher.py", line 108, in determine_the_libc
    self.select_libc()
  File "/home/yc0313/.local/lib/python3.8/site-packages/LibcSearcher/LibcSearcher.py", line 76, in select_libc
    print(str(index) + " - " + libc['id'])
TypeError: string indices must be integers
想问下是不是服务器挂了，作者看到麻烦能否修复一下

**Comment by rick1019** [comment]
> 

我也是这个问题，我听别的师傅说是服务器挂掉了

**Comment by yc0313** [comment]
> > 
> 
> 我也是这个问题，我听别的师傅说是服务器挂掉了

哦哦！我说呢，不知道啥时候才能修好啊
